name: video_player_tizen
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Tizen.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/video_player
version: 2.4.4

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: VideoPlayerTizenPlugin
        fileName: video_player_tizen_plugin.h
        dartPluginClass: VideoPlayerTizen

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface: ^5.1.2

dependency_overrides:
  video_player_platform_interface: # 5.1.1
    git:
      url: https://github.com/tvip/flutter-plugins.git
      ref: 'version-2.4.0'
      path: packages/video_player/video_player_platform_interface

dev_dependencies:
  pigeon: ^6.0.1

environment:
  flutter: ">=2.0.0"
  sdk: ">=2.12.0<3.0.0"
